version: "3"
services:
  emotobooth:
    image: emotobooth:latest
    build:
      context: ./site
      dockerfile: ./docker/Dockerfile-build
    command: npm run start
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - "${PWD}/data/config.js:/usr/app/config.js"
      # - "${PWD}/data/credentials.json:/usr/src/app/site/credentials.json"
      - "${PWD}/data/in:/usr/app/in"
      - "${PWD}/data/out:/usr/app/out"
      - "${PWD}/data/out-print:/usr/app/out-print"
      - "${PWD}/data/out-photostrips:/usr/app/out-photostrips"
    links:
      - "redis:redis"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379